### ISSUE TITLE
Bump minimum VSCode version to 1.52

### ISSUE THREAD

**Issue by isc-bsaviano** [intersystems-community/vscode-objectscript-pack#16]
Language Server version 1.1.0 just went live and it requires VSCode 1.52 and above. The pack should match that

**Comment by gjsjohnmurray** [comment]
@isc-rsingh in the previous release of the pack I reduced the dependency from 1.50 to 1.43 so as to suit Katacoda. What is your view about this request from @isc-bsaviano

ccing @daimor @isc-jamien

**Comment by isc-rsingh** [comment]
@gjsjohnmurray please go to 1.52. Turns out we aren't able to use Katacoda going forward.
