### ISSUE TITLE
Consider adding more extensions to the pack

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript-pack#18]
Candidates:

- https://marketplace.visualstudio.com/items?itemName=intersystems-community.sqltools-intersystems-driver
- https://marketplace.visualstudio.com/items?itemName=georgejames.webterminal-vscode

@isc-bsaviano @isc-rsingh @daimor what do you think? We can discuss offline if you prefer, but I won't be attending the October meeting.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I'm against adding either of these extensions because they have dependencies that are outside the pack (SQLTools WebTerminal). Also, executing SQL queries is tangentially related to and not essential for ObjectScript development.

**Comment by isc-rsingh** [comment]
I tend to agree with @isc-bsaviano. However, if and when they use servermanager, I see value in having extension packs of their own to signify that synergy.

An argument could be made that someone working with InterSystems tech would be happy to have everything in the Marketplace related to our tech installed and available. My ears are open to this, but right now I lean towards keeping them separate, especially since the extensions in the current bundle are the only ones for which InterSystems offers any level of support.

**Comment by gjsjohnmurray** [comment]
> executing SQL queries is tangentially related to and not essential for ObjectScript development

I have encountered some ObjectScript development shops that use Embedded SQL (for example) extensively. Being able to explore the schema and test your SQL statements without having to go to Portal ought to be of interest to them.

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I agree with @isc-rsingh that if https://github.com/intersystems-community/sqltools-intersystems-driver/issues/8 was resolved then it would make sense to have an `InterSystems SQL Development Pack` that contains SQLTools, our driver and the server manager. I like the idea of keeping extension packs small and narrow in scope so end users  get exactly what they need to solve a problem without extension bloat.

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano the IRIS driver already declares a dependency on SQLTools, and once the driver can use Server Manager connections it'll probably declare that as a dependency too. So a pack containing only those 3 extensions won't yield any benefit. If I were developing on the InterSystems platform and using embedded SQL (or other forms of SQL) I'd want the ObjectScript extension and the IRIS SQLTools driver. For the best experience I should add Language Server (the ObjectScript extension will encourage installation of this anyway, but it's not an actual dependency). So a pack containing the IRIS SQLTools driver, the ObjectScript extension and the Language Server would be the minimum requirement (as the driver would pull in SQLTools and Server Manager).

I don't fully understand the resistance you and @isc-rsingh seem to have to a "blessed" extension pack including an open source extension hosted on the intersystems-community GH org and published on Marketplace under that org (the IRIS driver).

**Comment by isc-rsingh** [comment]
My biggest resistance @gjsjohnmurray is that the IRIS SQLTools driver is much less mature than other SQL options like DBeaver and SQuirrel. I agree that ObjectScript developers will more often than not doing a good deal of SQL work, but at the moment I hesitate to promote it in this way (although I hope we get to that point after heavier use in the wild). 

How about a compromise where we have a second "InterSystems Developer Extension Pack" that has everything? For now we can promote it as  individuals, and eventually we may start promoting that over the ObjectScript Pack?

**Comment by gjsjohnmurray** [comment]
> How about a compromise where we have a second "InterSystems Developer Extension Pack" that has everything?

I'm happy with that proposal. I agree it shouldn't happen until the driver is able to integrate with Server Manager 3 for connection definitions and secure storage of credentials.

**Comment by daimor** [comment]
I see no reason to include SQLTools driver in the pack, due to the reasonable lack of its functionality. It's too basic, and anyway requires one more extension, which in fact provides access to other kinds of databases. 
It would be ok if it were a standalone extension and would use xDBC connectivity to IRIS. At this time, it uses SQL over REST, and it's too simple, with many limits.

**Comment by daimor** [comment]
WebTerminal requires an additional third-party tool to be installed manually. I think not a good candidate too
