### ISSUE TITLE
Enabling the APIs

### ISSUE THREAD

**Issue by vaidhk** [intersystems-community/vscode-objectscript-pack#25]
Type: <b>Feature Request</b>

Added the lone on argv.json file and relaunched VS.

However the API is not available.

Extension version: 1.0.3
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by isc-bsaviano** [comment]
@vaidhk Did you follow all the steps listed [here](https://github.com/intersystems-community/vscode-objectscript?tab=readme-ov-file#enable-proposed-apis)?
