### ISSUE TITLE
Need assistance for installing the VS Code extension

### ISSUE THREAD

**Issue by vaidhk** [intersystems-community/vscode-objectscript-pack#26]
Type: <b>Feature Request</b>

Need assistance for installing the VS Code extension.

Extension version: 1.0.3
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by isc-bsaviano** [comment]
@vaidhk What part of the [install steps](https://docs.intersystems.com/components/csp/docbook/DocBook.UI.Page.cls?KEY=GVSCO_install#GVSCO_install_extensions) isn't working? Can you give me more details or a screenshot please?

**Comment by vaidhk** [comment]
@isc-bsaviano I was able to install the extension using the .vsix file. However I dont see the icon of the extension. I tried same on my local computer and the icon shows up.
<img width="748" alt="screenshot" src="https://github.com/user-attachments/assets/225abaa4-bfb5-45aa-a464-f65a1c988a0c">

**Comment by isc-bsaviano** [comment]
@vaidhk You somehow only have the extension pack installed, but not the extensions in the pack. The pack itself is empty, it just tells VS Code what extensions to install. Can you uninstall the pack and re-install it from the marketplace?

**Comment by vaidhk** [comment]
@isc-bsaviano Thanks, got the extensions installed now. Tried to uninstall and install back. Also upgraded the VS.

**Comment by isc-bsaviano** [comment]
I'm glad you got them installed!
