### ISSUE TITLE
Error while loading the server and namespace

### ISSUE THREAD

**Issue by vaidhk** [intersystems-community/vscode-objectscript-pack#27]
Type: <b>Feature Request</b>

Trying to connect to the server, selected the instance and provided details. Receiving errors
1) Non-JSON response to/healthconnect/api/atelier/reqquest is the web server suppressing detailed errors?
2)Failed to fetch namespace list from server

Extension version: 1.0.3
VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by vaidhk** [comment]
<img width="576" alt="Error" src="https://github.com/user-attachments/assets/ca144e9a-2fd0-489c-8ad8-1b9d39fd3c73">

**Comment by isc-bsaviano** [comment]
@vaidhk This means that one or both of these are true:
* You're connection info was wrong, and this response didn't come from IRIS
* Your our web server is configured to send its own error pages when an HTTP error was encountered, and an error was encountered.

**Comment by gjsjohnmurray** [comment]
@vaidhk please also note that the notification footer tells you which extension it comes from. In future it's best to raise your issue against that extension rather that against the extension pack.

**Comment by isc-bsaviano** [comment]
Closing due to staleness. @vaidhk Please re-open if you're still having issues
