### ISSUE TITLE
Add CI script and token to support releasing to Marketplace

### ISSUE THREAD

**Issue by gjsjohnmurray** [intersystems-community/vscode-objectscript-pack#8]
@daimor are you willing to take this? I guess you'll need help from @isc-rsingh to get the token in place, and to adjust settings on this repo. I don't expect frequent releases will be needed, since there's not much to fix or enhance in an extension pack. But having the CI in place seems like a good idea.

**Comment by daimor** [comment]
Yeah, sure

**Comment by gjsjohnmurray** [comment]
Thanks. And when working on the CI for this repo maybe see if you can make it handle the following release pathway.

1. Draft a release and save it as a draft.

![image](https://user-images.githubusercontent.com/6726799/96709301-6a081680-1392-11eb-987f-be9f2f6dc836.png)

2. Later, return to the draft release and use the "Publish release" button.

When I did this on the other repo yesterday step 2 didn't trigger the release workflow necessary to send a vsix to Marketplace.

**Comment by gjsjohnmurray** [comment]
@isc-rsingh please add the 3 secrets @daimor listed in PR #9 into this repo's Settings section.

Once those are in position I will create the first release of this extension pack.

**Comment by isc-rsingh** [comment]
Tokens added.

**Comment by gjsjohnmurray** [comment]
Thanks both. Now published.
